// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBiMbm0qUhPgmgH1fKdCj372qyCl1yldHE',
    appId: '1:718716078560:web:fc580fab585c9a9f208385',
    messagingSenderId: '718716078560',
    projectId: 'fair-app-test-2',
    authDomain: 'fair-app-test-2.firebaseapp.com',
    storageBucket: 'fair-app-test-2.appspot.com',
    measurementId: 'G-Y7B0DDT6PR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZoBJJJ5ahcbYngiHIEodR-zOzXGTglG0',
    appId: '1:718716078560:android:ac47395a337ab54c208385',
    messagingSenderId: '718716078560',
    projectId: 'fair-app-test-2',
    storageBucket: 'fair-app-test-2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB13oQOrp34WrnDcRD6T_994PERls9IpHo',
    appId: '1:718716078560:ios:695b5f74ad32a9eb208385',
    messagingSenderId: '718716078560',
    projectId: 'fair-app-test-2',
    storageBucket: 'fair-app-test-2.appspot.com',
    iosClientId:
        '718716078560-hdd09dbufiiu9vk1ia7cu77c63noo3dd.apps.googleusercontent.com',
    iosBundleId: 'com.example.fairApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB13oQOrp34WrnDcRD6T_994PERls9IpHo',
    appId: '1:718716078560:ios:695b5f74ad32a9eb208385',
    messagingSenderId: '718716078560',
    projectId: 'fair-app-test-2',
    storageBucket: 'fair-app-test-2.appspot.com',
    iosClientId:
        '718716078560-hdd09dbufiiu9vk1ia7cu77c63noo3dd.apps.googleusercontent.com',
    iosBundleId: 'com.example.fairApp',
  );
}
